#' OS Result Upload
#'
#' Upload the OS result with sample barcode to the LIMS
#' @import httr
#' @import jsonlite
#' @import dplyr
#' @import purrr
#' @param os The data OS data frame with barcode generated by OS_to_LIMS()
#' @param site The PFS version need to work on: "Test" or "Production"
#' @param ept_barcode The Experiment Barcode of samples
#' @param username The username to log in PFS
#' @param password The password to log in PFS
#' @return Return
#' @examples
#' UPLOAD_OS("Test", "LCMS1", "user", "password");
#' @export


UPLOAD_OS <- function(os, site, ept_barcode, username, password) {
  lims <- GET_LCMS_SampleBarcodes(site, ept_barcode, username, password)
}
