#' OS Result Upload
#'
#' Upload the OS result with sample barcode to the LIMS
#' @import httr
#' @import jsonlite
#' @import dplyr
#' @import purrr
#' @param os The data OS data frame with barcode generated by OS_to_LIMS()
#' @param site The PFS version need to work on: "Test" or "Production"
#' @param username The username to log in PFS
#' @param password The password to log in PFS
#' @return Return upload status message
#' @examples
#' UPLOAD_OS("Test", "LCMS1", "user", "password");
#' @export

UPLOAD_OS <- function(os, site, username, password) {

  os <- os |>
    filter(!str_detect(Match_Name, "Not Match|Duplicated Sample")) |>
    select(-`Sample Type`)
  colnames(os) <- gsub("\\s+", "_", toupper(colnames(os)))

  # Get values from LIMS
  if (site == "Test") {
    data("t_url", package = "NData", envir = environment())
    prefix <- t_url
  } else if (site == "Production") {
    data("p_url", package = "NData", envir = environment())
    prefix <- p_url
  }

  messages <- NULL
  for (i in os$EXPT_SAMPLE_BARCODE) {
    result <- os[os$EXPT_SAMPLE_BARCODE == i, ]
    url <- paste0(prefix, "LC_MSMS_ASSAY_DATA('", i, "')")
    response <- GET(url, authenticate(username, password))
    data <- fromJSON(content(response, "text"))
    common_cols <- intersect(colnames(os), names(data))
    for (j in common_cols) {
      data[[j]] <- ifelse(is.na(result[[j]]), data[[j]], result[[j]])
    }

    # Upload new values
    update_payload <- toJSON(data, auto_unbox = T, null = "null")
    header <- c("Content-Type" = "application/json", "If-Match" = "*")
    put_response <- PUT(url,
                        body = update_payload,
                        authenticate(username, password),
                        add_headers(header))

    if (put_response[["status_code"]] == 200) {
      message = data.frame(
        barcode = i,
        status = "Updating completed!"
      )
      messages <- rbind(messages, message)
    } else {
      message = data.frame(
        barcode = i,
        status = "Updating failed!"
      )
      messages <- rbind(messages, message)
    }
  }

  if ("Updating failed!" %in% messages$status) {
    fail <- messages$barcode[messages$status == "Updating failed!"]
    result <- paste0("Uploading completed except for ", fail)
  } else if (unique(messages$status) == "Updating completed!")
    result <- paste0("Uploading completed!")

  return(result)
}
